// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  type PublicPath =
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icons/icon-128.png"
    | "/icons/icon-16.png"
    | "/icons/icon-48.png"
    | "/icons/icon.svg"
  export interface ProjectRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
  }
}
